---
name: Build and run tests

'on':
  push:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build and run tests in docker
        run: docker build -t local/opengl_game_of_life .
